import type { DialogueNode } from "../simulation/types";

export const dialogues: Record<string, DialogueNode> = {
  opening: {
    id: "opening",
    speaker: "Raka",
    portraitKey: "player",
    text: "Looks like everyone's moving forward with their lives...",
    next: "opening-pressure",
  },
  "opening-pressure": {
    id: "opening-pressure",
    speaker: "Raka",
    portraitKey: "player",
    text: "Meanwhile, I'm still stuck here, trying to catch up with everything I haven't done yet.",
    next: "opening-shadow",
  },
  "opening-shadow": {
    id: "opening-shadow",
    speaker: "Shadow",
    portraitKey: "shadow",
    text: "If you stop now, they will move even further ahead.",
  },
  door: {
    id: "door",
    speaker: "Raka",
    portraitKey: "player",
    text: "The boarding house door is right there, but it feels far away when my head is still full of unfinished things.",
  },
  wardrobe: {
    id: "wardrobe",
    speaker: "Raka",
    portraitKey: "player",
    text: "Wow...",
    next: "wardrobe-exhausted",
  },
  "wardrobe-exhausted": {
    id: "wardrobe-exhausted",
    speaker: "Raka",
    portraitKey: "player",
    text: "I look exhausted.",
    next: "wardrobe-whatever",
  },
  "wardrobe-whatever": {
    id: "wardrobe-whatever",
    speaker: "Raka",
    portraitKey: "player",
    text: "Whatever.",
    next: "wardrobe-focused",
  },
  "wardrobe-focused": {
    id: "wardrobe-focused",
    speaker: "Raka",
    portraitKey: "player",
    text: "I need to stay focused.",
  },
  clock: {
    id: "clock",
    speaker: "Raka",
    portraitKey: "player",
    text: "The hands are small, but the sound feels like it is counting everything I have not done yet.",
  },
  chair: {
    id: "chair",
    speaker: "Raka",
    portraitKey: "player",
    text: "This chair knows the weight of my body better than the bed does. Maybe that is not something to be proud of.",
  },
  laptop: {
    id: "laptop",
    speaker: "Raka",
    portraitKey: "player",
    text: "The laptop, my notes, and the fear of falling behind all gather at the same desk. Just a little more. Just a little more.",
    next: "laptop-shadow",
  },
  "laptop-shadow": {
    id: "laptop-shadow",
    speaker: "Shadow",
    portraitKey: "shadow",
    text: "If you stop now, everyone else will move even further ahead.",
  },
  "money-50-vacancies": {
    id: "money-50-vacancies",
    speaker: "Raka",
    portraitKey: "player",
    text: "Hm, there are some job vacancy available.",
    next: "money-50-freelance",
  },
  "money-50-freelance": {
    id: "money-50-freelance",
    speaker: "Raka",
    portraitKey: "player",
    text: "Applying for freelance work would also be interesting!",
  },
  "money-125-applications": {
    id: "money-125-applications",
    speaker: "Raka",
    portraitKey: "player",
    text: "I've submitted so many applications already.",
    next: "money-125-lost-count",
  },
  "money-125-lost-count": {
    id: "money-125-lost-count",
    speaker: "Raka",
    portraitKey: "player",
    text: "I've honestly lost count.",
  },
  "money-275-keep-pushing": {
    id: "money-275-keep-pushing",
    speaker: "Raka",
    portraitKey: "player",
    text: "Maybe I just need to keep pushing a little more.",
  },
  "money-200-new-project": {
    id: "money-200-new-project",
    speaker: "Raka",
    portraitKey: "player",
    text: "Finally, a new project! I don't want to waste this opportunity.",
    next: "money-200-do-my-best",
  },
  "money-200-do-my-best": {
    id: "money-200-do-my-best",
    speaker: "Raka",
    portraitKey: "player",
    text: "I'll do my best.",
  },
  "money-350-has-to-work": {
    id: "money-350-has-to-work",
    speaker: "Raka",
    portraitKey: "player",
    text: "This has to work out. I cannot afford to fail again.",
    next: "money-350-cant-mess-up",
  },
  "money-350-cant-mess-up": {
    id: "money-350-cant-mess-up",
    speaker: "Raka",
    portraitKey: "player",
    text: "I can't mess this up either.",
  },
  "prayer-time-1": {
    id: "prayer-time-1",
    speaker: "Raka",
    portraitKey: "player",
    text: "Already?",
    next: "prayer-time-2",
  },
  "prayer-time-2": {
    id: "prayer-time-2",
    speaker: "Raka",
    portraitKey: "player",
    text: "Time really flies.",
    next: "prayer-time-3",
  },
  "prayer-time-3": {
    id: "prayer-time-3",
    speaker: "Raka",
    portraitKey: "player",
    text: "...",
    next: "prayer-time-4",
  },
  "prayer-time-4": {
    id: "prayer-time-4",
    speaker: "Raka",
    portraitKey: "player",
    text: "I'm almost done with this project",
    next: "prayer-time-5",
  },
  "prayer-time-5": {
    id: "prayer-time-5",
    speaker: "Raka",
    portraitKey: "player",
    text: "Just a little longer, then I'll go pray.",
  },
  "money-475-ugh": {
    id: "money-475-ugh",
    speaker: "Raka",
    portraitKey: "player",
    text: "Ugh...",
    next: "money-475-whats-wrong",
  },
  "money-475-whats-wrong": {
    id: "money-475-whats-wrong",
    speaker: "Raka",
    portraitKey: "player",
    text: "What..s.. wrong... with.. me....",
    next: "money-475-silence",
  },
  "money-475-silence": {
    id: "money-475-silence",
    speaker: "Raka",
    portraitKey: "player",
    text: ".....",
  },
  "parent-message-1": {
    id: "parent-message-1",
    speaker: "Mom",
    portraitKey: "parent",
    text: "Hi, son. It's been a while since your last visit. How have you been?",
    next: "parent-message-2",
  },
  "parent-message-2": {
    id: "parent-message-2",
    speaker: "Mom",
    portraitKey: "parent",
    text: "How's life in the city? You barely tell us what's going on these days.",
    next: "parent-message-3",
  },
  "parent-message-3": {
    id: "parent-message-3",
    speaker: "Mom",
    portraitKey: "parent",
    text: "Would you like to come home this weekend? We miss you.",
    next: "parent-message-4",
  },
  "parent-message-4": {
    id: "parent-message-4",
    speaker: "Mom",
    portraitKey: "parent",
    text: "Let us know if you'd like to visit. :)",
    next: "parent-reply-1",
  },
  "parent-reply-1": {
    id: "parent-reply-1",
    speaker: "Raka",
    portraitKey: "player",
    text: "Hi Mom... Sorry, I've been really busy lately.",
    next: "parent-reply-2",
  },
  "parent-reply-2": {
    id: "parent-reply-2",
    speaker: "Raka",
    portraitKey: "player",
    text: "But don't worry, I'm doing okay.",
  },
  "zulfan-message-1": {
    id: "zulfan-message-1",
    speaker: "Zulfan",
    portraitKey: "friend",
    text: "Hey, Raka!",
    next: "zulfan-message-2",
  },
  "zulfan-message-2": {
    id: "zulfan-message-2",
    speaker: "Zulfan",
    portraitKey: "friend",
    text: "Me, Royyan, and Irfan are going ice skating this weekend. Want to come with us?",
    next: "zulfan-message-3",
  },
  "zulfan-message-3": {
    id: "zulfan-message-3",
    speaker: "Zulfan",
    portraitKey: "friend",
    text: "You've been working nonstop lately. Take a break for once.",
    next: "zulfan-reply-1",
  },
  "zulfan-reply-1": {
    id: "zulfan-reply-1",
    speaker: "Raka",
    portraitKey: "player",
    text: "Bad timing, bro. Maybe next time.",
    next: "zulfan-reply-2",
  },
  "zulfan-reply-2": {
    id: "zulfan-reply-2",
    speaker: "Raka",
    portraitKey: "player",
    text: "Hope you guys have fun.",
  },
  "food-order-arrived": {
    id: "food-order-arrived",
    speaker: "Raka",
    portraitKey: "player",
    text: "That should be my food order. Finally.",
  },
  "food-order-enough": {
    id: "food-order-enough",
    speaker: "Raka",
    portraitKey: "player",
    text: "That should be enough for today.",
  },
  bed: {
    id: "bed",
    speaker: "Raka",
    portraitKey: "player",
    text: "There is no time to sleep. The bed can call all it wants, but the work is not done and I have to keep going.",
  },
  shadow: {
    id: "shadow",
    speaker: "Shadow",
    portraitKey: "shadow",
    text: "One hour with a friend could be the hour that makes you fall behind.",
  },
  friend: {
    id: "friend",
    speaker: "Dina",
    portraitKey: "friend",
    text: "Rak, come eat with us for a bit. You have been quiet this whole time. Just half an hour.",
    choices: [
      {
        label: "Refuse. I have to be productive.",
        next: "friend-reject",
        setFlags: ["rejectedFriend", "handledFriend"],
      },
      {
        label: "Later, after I finish my work.",
        next: "friend-later",
        setFlags: ["postponedFriend", "handledFriend"],
      },
      {
        label: "Stay silent and get back to work.",
        next: "friend-silent",
        setFlags: ["ignoredFriend", "handledFriend"],
      },
    ],
  },
  "friend-reject": {
    id: "friend-reject",
    speaker: "Raka",
    portraitKey: "player",
    text: "Sorry, Din. I cannot waste time right now.",
    next: "friend-hurt",
  },
  "friend-later": {
    id: "friend-later",
    speaker: "Raka",
    portraitKey: "player",
    text: "Later. I just need to finish this first.",
    next: "friend-hurt",
  },
  "friend-silent": {
    id: "friend-silent",
    speaker: "Raka",
    portraitKey: "player",
    text: "...",
    next: "friend-hurt",
  },
  "friend-hurt": {
    id: "friend-hurt",
    speaker: "Dina",
    portraitKey: "friend",
    text: "Okay. I will wait until you are done being human again.",
  },
  "parent-call": {
    id: "parent-call",
    speaker: "Mother",
    portraitKey: "parent",
    text: "Sweetheart, come home for a while. I saved your dinner. You sound tired.",
    choices: [
      {
        label: "Say you are still busy.",
        next: "parent-busy",
        setFlags: ["rejectedParent", "handledParentCall"],
      },
      {
        label: "Say you will come home later.",
        next: "parent-later",
        setFlags: ["postponedParent", "handledParentCall"],
      },
    ],
  },
  "parent-busy": {
    id: "parent-busy",
    speaker: "Raka",
    portraitKey: "player",
    text: "I am busy, Mom. Do not wait for me.",
    next: "parent-soft",
  },
  "parent-later": {
    id: "parent-later",
    speaker: "Raka",
    portraitKey: "player",
    text: "Soon, Mom. I promise.",
    next: "parent-soft",
  },
  "parent-soft": {
    id: "parent-soft",
    speaker: "Mother",
    portraitKey: "parent",
    text: "The same promise as yesterday. But all right. I will pray for you.",
  },
  "work-desk": {
    id: "work-desk",
    speaker: "Raka",
    portraitKey: "player",
    text: "My hands are shaking, but this progress bar is almost full. Just a little more. Just a little more.",
  },
  collapse: {
    id: "collapse",
    speaker: "Narration",
    portraitKey: "shadow",
    text: "The streetlights stretch into long lines. Notification sounds merge with a heartbeat. Then everything stops.",
  },
  "replay-friend": {
    id: "replay-friend",
    speaker: "Recording",
    portraitKey: "friend",
    text: "If Raka had accepted Dina's invitation, that night would have been only half an hour. But he would have gone home with a small laugh that made tomorrow feel possible.",
    next: "replay-friend-self",
  },
  "replay-friend-self": {
    id: "replay-friend-self",
    speaker: "Raka",
    portraitKey: "player",
    text: "I thought resting would make me lose. It turns out I was just afraid of being seen standing still.",
  },
  "replay-parent": {
    id: "replay-parent",
    speaker: "Recording",
    portraitKey: "parent",
    text: "If Raka had gone home, dinner might have been ordinary. But someone would have looked at his face and said, enough for today.",
    next: "replay-parent-self",
  },
  "replay-parent-self": {
    id: "replay-parent-self",
    speaker: "Raka",
    portraitKey: "player",
    text: "I chased the future until I forgot there were people waiting for me in the present.",
  },
  "final-question": {
    id: "final-question",
    speaker: "Shadow",
    portraitKey: "shadow",
    text: "You have chased everything. Now answer this: what are you really chasing?",
    next: "final-answer",
  },
  "final-answer": {
    id: "final-answer",
    speaker: "Raka",
    portraitKey: "player",
    text: "I want to live. Not just prove that I deserve to live.",
  },
};
