import type { DialogueNode } from "../simulation/types";

export const dialogues: Record<string, DialogueNode> = {
  opening: {
    id: "opening",
    speaker: "Raka",
    portraitKey: "player",
    text: "Semua orang bergerak cepat. Kalau aku berhenti sebentar saja, aku akan tertinggal.",
    next: "opening-shadow",
  },
  "opening-shadow": {
    id: "opening-shadow",
    speaker: "Bayangan",
    portraitKey: "shadow",
    text: "Mereka sudah magang. Mereka sudah punya portofolio. Mereka sudah jadi sesuatu.",
  },
  laptop: {
    id: "laptop",
    speaker: "Raka",
    portraitKey: "player",
    text: "Deadline, kursus, lomba, side project. Kalau malam ini selesai, mungkin besok aku bisa bernapas.",
    next: "laptop-shadow",
  },
  "laptop-shadow": {
    id: "laptop-shadow",
    speaker: "Bayangan",
    portraitKey: "shadow",
    text: "Besok? Orang lain sudah mulai hari ini.",
  },
  calendar: {
    id: "calendar",
    speaker: "Raka",
    portraitKey: "player",
    text: "Tidak ada ruang kosong. Kalau ada ruang kosong, berarti aku belum cukup berusaha.",
  },
  mirror: {
    id: "mirror",
    speaker: "Raka",
    portraitKey: "player",
    text: "Mataku merah. Tapi ini harga yang wajar, kan? Orang sukses juga begini.",
    next: "mirror-shadow",
  },
  "mirror-shadow": {
    id: "mirror-shadow",
    speaker: "Bayangan",
    portraitKey: "shadow",
    text: "Jangan manja. Lelah itu cuma tanda kamu belum terbiasa.",
  },
  shadow: {
    id: "shadow",
    speaker: "Bayangan",
    portraitKey: "shadow",
    text: "Satu jam main sama teman bisa jadi satu jam yang membuatmu kalah.",
  },
  friend: {
    id: "friend",
    speaker: "Dina",
    portraitKey: "friend",
    text: "Rak, kita makan bentar yuk. Kamu dari tadi diam terus. Setengah jam aja.",
    choices: [
      {
        label: "Tolak. Aku harus produktif.",
        next: "friend-reject",
        setFlags: ["rejectedFriend", "handledFriend"],
        regretDelta: 2,
      },
      {
        label: "Nanti ya, kalau tugasku selesai.",
        next: "friend-later",
        setFlags: ["postponedFriend", "handledFriend"],
        regretDelta: 1,
      },
      {
        label: "Diam dan kembali kerja.",
        next: "friend-silent",
        setFlags: ["ignoredFriend", "handledFriend"],
        regretDelta: 2,
      },
    ],
  },
  "friend-reject": {
    id: "friend-reject",
    speaker: "Raka",
    portraitKey: "player",
    text: "Maaf, Din. Aku nggak bisa buang waktu sekarang.",
    next: "friend-hurt",
  },
  "friend-later": {
    id: "friend-later",
    speaker: "Raka",
    portraitKey: "player",
    text: "Nanti ya. Aku cuma perlu selesain ini dulu.",
    next: "friend-hurt",
  },
  "friend-silent": {
    id: "friend-silent",
    speaker: "Raka",
    portraitKey: "player",
    text: "...",
    next: "friend-hurt",
  },
  "friend-hurt": {
    id: "friend-hurt",
    speaker: "Dina",
    portraitKey: "friend",
    text: "Oke. Aku tunggu kamu selesai jadi manusia lagi.",
  },
  "parent-call": {
    id: "parent-call",
    speaker: "Ibu",
    portraitKey: "parent",
    text: "Nak, pulang dulu. Makan malammu masih Ibu simpan. Kamu terdengar capek.",
    choices: [
      {
        label: "Bilang masih sibuk.",
        next: "parent-busy",
        setFlags: ["rejectedParent", "handledParentCall"],
        regretDelta: 2,
      },
      {
        label: "Bilang nanti pulang.",
        next: "parent-later",
        setFlags: ["postponedParent", "handledParentCall"],
        regretDelta: 1,
      },
    ],
  },
  "parent-busy": {
    id: "parent-busy",
    speaker: "Raka",
    portraitKey: "player",
    text: "Aku lagi sibuk, Bu. Jangan tunggu aku.",
    next: "parent-soft",
  },
  "parent-later": {
    id: "parent-later",
    speaker: "Raka",
    portraitKey: "player",
    text: "Sebentar lagi, Bu. Aku janji.",
    next: "parent-soft",
  },
  "parent-soft": {
    id: "parent-soft",
    speaker: "Ibu",
    portraitKey: "parent",
    text: "Janji yang sama seperti kemarin. Tapi ya sudah, Ibu doakan.",
  },
  "work-desk": {
    id: "work-desk",
    speaker: "Raka",
    portraitKey: "player",
    text: "Tanganku gemetar, tapi progres bar ini hampir penuh. Sedikit lagi. Sedikit lagi.",
    next: "collapse",
  },
  collapse: {
    id: "collapse",
    speaker: "Narasi",
    portraitKey: "shadow",
    text: "Lampu jalan menjadi garis panjang. Suara notifikasi menyatu dengan detak jantung. Lalu semuanya berhenti.",
  },
  "replay-friend": {
    id: "replay-friend",
    speaker: "Rekaman",
    portraitKey: "friend",
    text: "Jika Raka menerima ajakan Dina, malam itu hanya setengah jam. Tapi ia pulang dengan tawa kecil yang membuat besok terasa mungkin.",
    next: "replay-friend-self",
  },
  "replay-friend-self": {
    id: "replay-friend-self",
    speaker: "Raka",
    portraitKey: "player",
    text: "Aku kira istirahat akan membuatku kalah. Ternyata aku cuma takut dilihat tidak berlari.",
  },
  "replay-parent": {
    id: "replay-parent",
    speaker: "Rekaman",
    portraitKey: "parent",
    text: "Jika Raka pulang, makan malam itu mungkin biasa saja. Tapi ada seseorang yang melihat wajahnya dan berkata, cukup untuk hari ini.",
    next: "replay-parent-self",
  },
  "replay-parent-self": {
    id: "replay-parent-self",
    speaker: "Raka",
    portraitKey: "player",
    text: "Aku mengejar masa depan sampai lupa ada orang yang menungguku di masa sekarang.",
  },
  "final-question": {
    id: "final-question",
    speaker: "Bayangan",
    portraitKey: "shadow",
    text: "Kamu sudah mengejar semuanya. Sekarang jawab: apa yang sebenarnya kamu kejar?",
    next: "final-answer",
  },
  "final-answer": {
    id: "final-answer",
    speaker: "Raka",
    portraitKey: "player",
    text: "Aku ingin hidup. Bukan cuma membuktikan bahwa aku pantas hidup.",
  },
};
