import type { RoomDefinition } from "../simulation/types";

export const rooms: Record<string, RoomDefinition> = {
  bedroom: {
    id: "bedroom",
    title: "Kamar Raka",
    backgroundKey: "room.bedroom",
    playerStart: { x: 330, y: 486 },
    interactables: [
      {
        id: "door",
        label: "Pintu",
        kind: "object",
        x: 160,
        y: 486,
        radius: 130,
        dialogueId: "door",
        onCompleteFlags: ["checkedDoor"],
        repeatable: true,
      },
      {
        id: "laptop",
        label: "Laptop",
        kind: "object",
        x: 600,
        y: 350,
        radius: 180,
        dialogueId: "laptop",
        onCompleteFlags: ["checkedLaptop"],
        startsDeskMinigame: true,
        repeatable: true,
      },
      {
        id: "bed",
        label: "Kasur",
        kind: "object",
        x: 860,
        y: 428,
        radius: 100,
        dialogueId: "bed",
        onCompleteFlags: ["checkedBed"],
        repeatable: true,
      },
    ],
  },
  street: {
    id: "street",
    title: "Jalan Pulang",
    backgroundKey: "room.street",
    playerStart: { x: 118, y: 386 },
    interactables: [
      {
        id: "friend",
        label: "Dina",
        kind: "npc",
        x: 318,
        y: 382,
        radius: 58,
        dialogueId: "friend",
      },
      {
        id: "parent-call",
        label: "Telepon Ibu",
        kind: "object",
        x: 598,
        y: 386,
        radius: 52,
        dialogueId: "parent-call",
      },
      {
        id: "work-desk",
        label: "Meja Kerja 24 Jam",
        kind: "object",
        x: 790,
        y: 348,
        radius: 68,
        dialogueId: "work-desk",
        requiredFlags: ["handledFriend", "handledParentCall"],
        startsDeskMinigame: true,
        afterMinigameDialogueId: "collapse",
      },
      {
        id: "pressure-shadow",
        label: "Orang-orang Yang Lebih Cepat",
        kind: "shadow",
        x: 706,
        y: 384,
        radius: 60,
        dialogueId: "shadow",
        repeatable: true,
      },
    ],
  },
  replay: {
    id: "replay",
    title: "Rekaman Hidup",
    backgroundKey: "room.replay",
    playerStart: { x: 480, y: 386 },
    interactables: [
      {
        id: "replay-friend",
        label: "What if: Dina",
        kind: "npc",
        x: 282,
        y: 372,
        radius: 66,
        dialogueId: "replay-friend",
        onCompleteFlags: ["sawReplayFriend"],
      },
      {
        id: "replay-parent",
        label: "What if: Rumah",
        kind: "npc",
        x: 504,
        y: 372,
        radius: 66,
        dialogueId: "replay-parent",
        onCompleteFlags: ["sawReplayParent"],
      },
      {
        id: "final-question",
        label: "Pertanyaan Terakhir",
        kind: "shadow",
        x: 728,
        y: 370,
        radius: 70,
        dialogueId: "final-question",
        requiredFlags: ["sawReplayFriend", "sawReplayParent"],
        onCompleteFlags: ["answeredFinalQuestion"],
      },
    ],
  },
};
