import type { RoomDefinition } from "../simulation/types";

export const rooms: Record<string, RoomDefinition> = {
  bedroom: {
    id: "bedroom",
    title: "Kamar Raka",
    backgroundKey: "room.bedroom",
    playerStart: { x: 160, y: 386 },
    interactables: [
      {
        id: "laptop",
        label: "Laptop",
        kind: "object",
        x: 520,
        y: 338,
        radius: 58,
        dialogueId: "laptop",
        onCompleteFlags: ["checkedLaptop"],
      },
      {
        id: "calendar",
        label: "Kalender",
        kind: "object",
        x: 710,
        y: 210,
        radius: 52,
        dialogueId: "calendar",
        onCompleteFlags: ["checkedCalendar"],
      },
      {
        id: "mirror",
        label: "Cermin",
        kind: "object",
        x: 258,
        y: 282,
        radius: 48,
        dialogueId: "mirror",
        onCompleteFlags: ["checkedMirror"],
      },
      {
        id: "shadow",
        label: "Bayangan",
        kind: "shadow",
        x: 770,
        y: 374,
        radius: 54,
        dialogueId: "shadow",
        requiredFlags: ["checkedLaptop"],
        repeatable: true,
      },
    ],
  },
  street: {
    id: "street",
    title: "Jalan Pulang",
    backgroundKey: "room.street",
    playerStart: { x: 118, y: 386 },
    interactables: [
      {
        id: "friend",
        label: "Dina",
        kind: "npc",
        x: 318,
        y: 382,
        radius: 58,
        dialogueId: "friend",
      },
      {
        id: "parent-call",
        label: "Telepon Ibu",
        kind: "object",
        x: 598,
        y: 386,
        radius: 52,
        dialogueId: "parent-call",
      },
      {
        id: "work-desk",
        label: "Meja Kerja 24 Jam",
        kind: "object",
        x: 790,
        y: 348,
        radius: 68,
        dialogueId: "work-desk",
        requiredFlags: ["handledFriend", "handledParentCall"],
      },
      {
        id: "pressure-shadow",
        label: "Orang-orang Yang Lebih Cepat",
        kind: "shadow",
        x: 706,
        y: 384,
        radius: 60,
        dialogueId: "shadow",
        repeatable: true,
      },
    ],
  },
  replay: {
    id: "replay",
    title: "Rekaman Hidup",
    backgroundKey: "room.replay",
    playerStart: { x: 480, y: 386 },
    interactables: [
      {
        id: "replay-friend",
        label: "What if: Dina",
        kind: "npc",
        x: 282,
        y: 372,
        radius: 66,
        dialogueId: "replay-friend",
        onCompleteFlags: ["sawReplayFriend"],
      },
      {
        id: "replay-parent",
        label: "What if: Rumah",
        kind: "npc",
        x: 504,
        y: 372,
        radius: 66,
        dialogueId: "replay-parent",
        onCompleteFlags: ["sawReplayParent"],
      },
      {
        id: "final-question",
        label: "Pertanyaan Terakhir",
        kind: "shadow",
        x: 728,
        y: 370,
        radius: 70,
        dialogueId: "final-question",
        requiredFlags: ["sawReplayFriend", "sawReplayParent"],
        onCompleteFlags: ["answeredFinalQuestion"],
      },
    ],
  },
};
