import type { AssetManifest } from "../game/simulation/types";

export const assetManifest: AssetManifest = {
  characters: {
    "character.player": "/assets/characters/player/Sprite_0006.png",
    "character.player.walk.right.0": "/assets/characters/player/Sprite_00010.png",
    "character.player.walk.right.1": "/assets/characters/player/Sprite_00011.png",
    "character.player.walk.right.2": "/assets/characters/player/Sprite_00012.png",
    "character.player.walk.right.3": "/assets/characters/player/Sprite_00013.png",
    "character.player.walk.right.4": "/assets/characters/player/Sprite_00014.png",
    "character.player.walk.right.5": "/assets/characters/player/Sprite_00015.png",
    "character.player.walk.left.0": "/assets/characters/player/Sprite_0003.png",
    "character.player.walk.left.1": "/assets/characters/player/Sprite_0004.png",
    "character.player.walk.left.2": "/assets/characters/player/Sprite_0005.png",
    "character.player.idle.mirror": "/assets/characters/player/Sprite_0004.png",
    "character.player.walk.down.0": "/assets/characters/player/Sprite_0006.png",
    "character.player.walk.down.1": "/assets/characters/player/Sprite_0007.png",
    "character.player.walk.up.0": "/assets/characters/player/Sprite_0008.png",
    "character.player.walk.up.1": "/assets/characters/player/Sprite_0009.png",
    "npc.friend": "procedural/friend",
    "npc.parent": "procedural/parent",
    "npc.shadow": "procedural/shadow",
  },
  rooms: {
    "room.bedroom": "procedural/bedroom",
    "room.bedroom.base": "/assets/environment/bedroom/base.png",
    "room.bedroom.laptopBlueLight": "/assets/environment/bedroom/blue-screen-effect.png",
    "room.bedroom.bed": "/assets/environment/bedroom/bed.png",
    "room.bedroom.chair": "/assets/environment/bedroom/chair.png",
    "room.bedroom.clock": "/assets/environment/bedroom/clock.png",
    "room.bedroom.clock.1": "/assets/environment/bedroom/clock/BG_Clock_1.png",
    "room.bedroom.clock.2": "/assets/environment/bedroom/clock/BG_Clock_2.png",
    "room.bedroom.clock.3": "/assets/environment/bedroom/clock/BG_Clock_3.png",
    "room.bedroom.clock.4": "/assets/environment/bedroom/clock/BG_Clock_4.png",
    "room.bedroom.desk": "/assets/environment/bedroom/desk.png",
    "room.bedroom.door": "/assets/environment/bedroom/door.png",
    "room.bedroom.nightOverlay": "/assets/environment/bedroom/BG_Nighttime_Multiply.png",
    "room.bedroom.preview": "/assets/environment/bedroom/preview.png",
    "room.bedroom.wardrobe": "/assets/environment/bedroom/wardrobe.png",
    "room.street": "procedural/street",
    "room.replay": "procedural/replay",
  },
  ui: {
    "ui.textbox": "dom/textbox",
    "ui.interact": "procedural/interact",
    "ui.mail": "/assets/ui/mail.png",
    "ui.mosque": "/assets/ui/kubah.png",
  },
  audio: {
    "sfx.player.footstep": "/assets/audio/footstep.wav",
    "sfx.door.bell": "/assets/audio/door-bell.wav",
    "sfx.door.knock": "/assets/audio/door-knock.wav",
    "sfx.door.rustle": "/assets/audio/door-rustle.wav",
    "sfx.keyboard.tap": "/assets/audio/spacebar.mp3",
    "sfx.money.earn": "/assets/audio/earn-money.mp3",
    "sfx.bubble.popup": "/assets/audio/pop-up-bubble-icon.mp3",
    "sfx.prayer.adzan": "/assets/audio/sound-adzan.wav",
    "sfx.environment.cricket": "/assets/audio/cricket.mp3",
    "sfx.environment.chicken": "/assets/audio/chicken.mp3",
    "bgm.phase1": "/assets/audio/backsound-phase1.mp3",
  },
};
